[tool.poetry]
name = "Appdaemon-Test-Framework"
version = "4.0.0"
description = ""
authors = ["Flo Kempenich <flo@kempenich.dev>"]
packages = [{include = "appdaemontestframework"}]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.dependencies]
python = "3.8.16"
appdaemon = "4.0.8"

[tool.poetry.group.dev.dependencies]
black = "23.3.0"
flake8 = "6.0.0"
flake8-isort = "6.0.0"
ipython = "8.12.0"
ipdb = "0.13.13"
mypy = "1.2.0"
pydocstyle = "6.3.0"
pylint = "2.17.3"
pytest = "7.3.1"
pytest-asyncio = "^0.21.0"
pytest-cov = "4.0.0"
pytest-mock = "3.10.0"
pytest-xdist = "3.2.1"
tox = "3.8.1"
